name: torrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.3.0
repository: https://github.com/eclipseglory/torrent_task
issue_tracker: https://github.com/eclipseglory/torrent_task/issues
publish_to: https://pub.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  torrent_model: ^1.0.4
  torrent_tracker: ^1.3.13
  dht_dart: ^0.0.8
  dartorrent_common: ^1.0.4
  bencode_dart: ^1.0.3
  utp: ^1.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
